# Generated by Django 5.2.9 on 2025-12-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0002_solciallink_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolcialLink',
            new_name='SocialLink',
        ),
    ]
